### ISSUE TITLE
[Bug/Feature request] tokens with a hidden score banked can't be hear 

### ISSUE THREAD

**Issue by TheXeno30** [dev7355608/vision-5e#83] opened 2024-06-07 15:57 UTC
So.. usecase

I have token1 in the dark that another token2 can hear. If token1 hides then token2 can no long hear token1. all good.

If Token2 then spots token1 (aka. have a higher spot than token1s hide score) token 2 still can't hear token1. 

hope it's clear :)

**Comment by dev7355608** [comment] 2024-06-07 16:14
It sounds like there is another module involved here, right? Stealthy, I assume?

**Comment by dev7355608** [comment] 2024-06-07 21:26
I suspect it is an issue with Stealthy: from your description it sounds like vision is not refreshed when the spot scores change. Vision 5e is unaware of Stealthy's spot scores.

**Comment by Eligarf** [comment] 2024-06-10 15:54
From Stealthy's side, I just tested this with a PC that could only hear the NPCs around it. I then used Stealthy to bank a middling stealth roll for one of the NPCs and the PC could no longer hear it. I then rolled a high perception check with the PC and it could hear the stealthed NPC again. I cannot repro the issue that you are having TheXeno30.

There is a separate issue where hearing doesn't seem to work anymore in v12 regardless of Stealthy being active or not.

**Comment by TheXeno30** [comment] 2024-06-10 20:52
Well - it might be my settings. So this is my setup. hope it helps.

Foundr V11.315
DnD 3.2.0
Chrome Version 125.0.6422.142

Active Modules:
Ace Library v;
Active Auras v;
Active Token Effects v;
Advanced Macros v;
Animated Dice Pack - TheRipper93 Premium Dice (Early Access) v;
Argon - Combat HUD (CORE) v;
Argon - Combat HUD (DND5E) v;
Arka Stream for Dice So Nice v;
Arms Reach v;
Automated Animations v;
Auto-Rotate v;
Baileywiki Mass Edit v;
Bar Brawl v;
Better Roll Tables v;
Better Roofs v;
Border Control v;
Break Time v;
Build-a-Bonus v;
Carousel Combat Tracker v;
Cayden's Dice v;
Chat Commander v;
Chat Images v;
Chris's Premades v;
Color Picker v;
Combat Booster: Turn Marker, Recent Actions and more v;
Compact Scene Navigation v;
Compendium Folders v;
D&D5e Animations v;
Designer Doors v;
DFreds Convenient Effects v;
Dice So Nice! v;
Dice So Nice - Weighted Companion Cube Dice Set v;
Dice Tray v;
DnDshared (Shared Compendiums) v;
Downtime (Dnd5e) v;
Drag Ruler v;
Dynamic Active Effects SRD v;
Dynamic effects using Active Effects (DAE) v;
Effect Macro v;
Epic Rolls 5e v;
Falemos (let's talk) v;
Filepicker + v;
Find the Culprit v;
Foundry VTT Anniversary Dice Set by The Rollsmith v;
FXMaster v;
Gambit's Premades v;
Gatherer v;
Handyfon's Dice Addiction v;
Hey, Wait! v;
Hover Distance v;
Image Context v;
Inactive Tokens v;
Item Macro v;
Item Piles v;
Jack Kerouac's Animated Spell Effects v;
JB2A - Patreon Complete Collection v;
Jinker's Animated Art Pack v;
Levels v;
Levels - Automatic Cover Calculator v;
Levels - Volumetric Templates v;
lib - Color Settings v;
Library: Scene Packer v;
libWrapper v;
LiveKit AVClient v;
Lordu's Custom Dice for Dice So Nice v;
Mastercrafted - Crafting Manager v;
Material Components v;
Maxwell's Manual of Malicious Maladies v;
Midi QOL v;
Midi SRD v;
Minimal UI v;
Monk's Active Tile Triggers v;
Monk's Bloodsplats v;
Monk's Combat Details v;
Monk's Enhanced Journal v;
Monk's Hotbar Expansion v;
Monk's Little Details v;
Monk's Player Settings v;
Monk's Scene Navigation v;
Monk's TokenBar v;
Monk's Wall Enhancement v;
More SFX Triggers for Dice So Nice v;
Moulinette Compendiums (module) v;
Moulinette Core v;
Moulinette Game Icons (module) v;
Moulinette Image Search (module) v;
Moulinette Scenes (module) v;
Moulinette Tiles (module) v;
Phandelver & Below: The Shattered Obelisk v;
Plutonium v;
Plutonium Addon: Automation v;
Point of Interest Teleporter v;
PopOut! v;
Potion Crafting & Gathering v;
Puzzle Locks v;
Quick Insert - Search Widget v;
QuickScale v;
Rideable v;
routinglib v;
Select tool everywhere v;
Sequencer v;
Show Token Art v;
Simple Calendar v;
Simple Quest v;
SmallTime v;
Smart Doors v;
Smart Target v;
socketlib v;
Splatter v;
Spotlight Omnisearch v;
Stealthy v;
Syrinscape Control v;
Tagger v;
Talis Dice v;
Template Macro v;
The Forge v;
The Forge: More Awesomeness v;
TheRipper93's Module Hub v;
The Rollsmith - A House Divided Dice Set v;
The Rollsmith - Black Marble Dice Set v;
The Rollsmith - Dragon Drogon Dice Set v;
The Rollsmith - Gold Ore Dice Set v;
The Rollsmith - Iridescent Rainbow Dice Set v;
The Rollsmith - Ruby Dice Set v;
Tidbits v;
Tidy UI - Game Settings v;
Tile Scroll v;
Tile Sort v;
Times Up v;
Token Attacher v;
Token Elevator v;
Token Magic FX v;
Token Variant Art v;
Vision 5e v;
Visual Active Effects v;
Walled Templates v;
Wall Height v;
Warp Gate v;
Wave Dice - TheRipper93 Premium Dice (Supporter) v;
WikiRole for Dice So Nice v;
WTF: What the Flag? v;

Inactive Modules:
About Time v;
CotO Addons v;
Crown of the Oathbreaker v;
Items with Spells DnD5e v;
Macro Editor v;
Perceptive v;
Power Select Toolkit v;

**Comment by dev7355608** [comment] 2024-06-10 21:33
> From Stealthy's side, I just tested this with a PC that could only hear the NPCs around it. I then used Stealthy to bank a middling stealth roll for one of the NPCs and the PC could no longer hear it. I then rolled a high perception check with the PC and it could hear the stealthed NPC again. I cannot repro the issue that you are having TheXeno30.

@Eligarf: I assumed @TheXeno30 is describing a situation where the controlled token isn't changed, and so this bug isn't something the GM would notice as they probably change control of tokens after changing the spot values. So I suspected that perhaps Stealthy doesn't call `canvas.perception.update({ refreshVision: true })` after the spot values have changed, or perhaps not in all cases at least. I didn't do any testing myself though, just a theory.

**Comment by TheXeno30** [comment] 2024-06-10 22:03
1. GM view - Invisible creature
![image](https://github.com/dev7355608/vision-5e/assets/135822719/3ab2132f-51ce-48df-b55a-71b16bc1cb8a)
2. Player view - invisible creature
![image](https://github.com/dev7355608/vision-5e/assets/135822719/f41f71aa-61b1-4922-8ea0-79ad37d55c0e)
3. Invisible creature also hiding
![image](https://github.com/dev7355608/vision-5e/assets/135822719/120f526e-b99a-4023-be21-25ecedd74a75)
![image](https://github.com/dev7355608/vision-5e/assets/135822719/3b020337-b5f6-46e4-aa23-7fb6285d9ae1)
4. Player token with spot above hide value - Here it should display sound again but not vision
![image](https://github.com/dev7355608/vision-5e/assets/135822719/142ca9b5-1e42-45f4-b8e6-0f72ec74aa2b)
![image](https://github.com/dev7355608/vision-5e/assets/135822719/00363a5d-e1ca-4d8c-83a8-3f3dfde2d35b)

**Comment by Eligarf** [comment] 2024-06-10 22:34
@dev7355608 : A perception refresh is done anytime perception or stealth is rolled, updated via the token HUD, or changed from some outside source like Perceptive. so I don't think the controlled token changing is a factor, but something is clearly going amiss.

@TheXeno30 : Can you do that sequence again but enable the debug logging in Stealthy's game settings? You can reply to me in the bug you opened on Stealthy [bug #139](https://github.com/Eligarf/stealthy/issues/139)

**Comment by dev7355608** [comment] 2024-06-16 14:12
@TheXeno30 Could you check whether Vision 5e 2.3.1 fixed this issue? I fixed a bug (#85) that might also be the root cause of this issue.

**Comment by TheXeno30** [comment] 2024-06-16 14:55
![image](https://github.com/dev7355608/vision-5e/assets/135822719/fa01d491-4fa1-4974-91de-88a0f9ad1116)
![image](https://github.com/dev7355608/vision-5e/assets/135822719/0ecf0b99-427b-4a68-97a6-b982d097ec20)
![image](https://github.com/dev7355608/vision-5e/assets/135822719/d6fa0894-02f8-437f-b593-5ccbd48c9993)
![image](https://github.com/dev7355608/vision-5e/assets/135822719/99875781-a6aa-4d50-9c55-cf7da40eefed)
![image](https://github.com/dev7355608/vision-5e/assets/135822719/b3d10494-8c76-427d-a53a-3ccd9659b3c7)

Using perceptive now. not stealthy. same issue.

**Comment by TheXeno30** [comment] 2024-06-16 15:01
funny thing...
If i beat the stealth it reveals the token even if invisible.
![image](https://github.com/dev7355608/vision-5e/assets/135822719/5ae124a9-3f4e-421c-8390-2f78f1ed2bc1)
but if I remove the hide effect it does doesn't show the token until i mouse over it then it shows the sounds
![image](https://github.com/dev7355608/vision-5e/assets/135822719/fa06dd4b-cb0e-4fd2-8d24-63e3bf80f3e0)

**Comment by TheXeno30** [comment] 2024-06-16 15:13
think i got it to work now - by messing around with settings - still reveals the token if you spot it - even invisible (guess its ok) and doesn't update until you move or mouseover the token if you remove hide.

**Comment by dev7355608** [comment] 2024-06-16 16:09
> Using perceptive now. not stealthy. same issue.

@TheXeno30 I checked Perception's source code a bit: I'm not confident that Perceptive and Vision 5e are a 100% compatible the way Perceptive is implemented. I suspect also Perceptive compatibility issues with other modules that do something vision related like GM Vision and Reveal Observable Tokens. I also cannot find evidence that Perception is refreshing vision/visibility anywhere.

**Comment by dev7355608** [comment] 2024-09-01 00:36
I'm closing this issue. Not sure what the currently compatibility status of Vision 5e + Perceptive is. If there still are, these issues need to be addressed by Perceptive most likely.

**Closed by dev7355608** 2024-09-01 00:36 UTC
